#
# Site settings
#
remote_theme: CamilleBC/pretty-docs
url: https://camillebc.github.io/android-basics-kotlin
base_url: ""
title: &site_title Android Basics
description: &site_description Tutorials to learn Android with Kotlin!
branding:
  icon:
    name: icon_documents_alt
  highlight: Android
  bold: Tutorial
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: Camille Bailalt
  copyright:
    notice: "[MIT license](https://opensource.org/licenses/MIT)"
    author: "[Camille Baillat](https://camillebc.github.io/)"

#
# Social
#
share:
  github:
      repo: CamilleBC/android-kotlin-basics
      position: right
      color: red

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
